### ISSUE TITLE
Newest commit produces error

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/lite-updater#2]
```
test32up@test32up-VirtualBox:/usr/bin$ ./lite-updater
Traceback (most recent call last):
  File "./lite-updater", line 281, in <module>
    app = Liteupdater()
  File "./lite-updater", line 57, in __init__
    'upgrade': 'Updates available' + " " + str(self.count_update()),
  File "./lite-updater", line 243, in count_update
    chosen_package = apt_cache[package_name]
UnboundLocalError: local variable 'apt_cache' referenced before assignment
test32up@test32up-VirtualBox:/usr/bin$ 
```

**Comment by shaggytwodope** [comment]
What commit hash?

**Comment by linuxlite** [comment]
I just pulled in your most recent - https://github.com/shaggytwodope/lite-updater/archive/master.zip

**Comment by shaggytwodope** [comment]
90d1e23 should fix this
